from cocapi.client import Client

TOKEN = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjcwMmM3YTQ3LTVjN2ItNDExYy04OTc2LWZiNjU3YTBkMDU1ZCIsImlhdCI6MTY0NTM3MTA0MSwic3ViIjoiZGV2ZWxvcGVyLzExY2MwYjA5LTFmNWEtNmMyNi0xNGY1LTRmNzA3OGRmN2YwNiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwOS4yNTIuMTE4LjIxNiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.tI12LhdoMCj8jtbYRf0nmQwSD6Hf_FY4Kxxc-99bx8gV5bKNi72MnASliH4SWc6j_O3VD8Z-Fut2BREezJr_Pw'

coc = Client(TOKEN)

clans = coc.clans(name='bomb', location='ru', max_members=30)
print(clans)

coc.close()
