# type: ignore
# pylint: disable-all

import pytest

import pytest_asyncio

from cocapi import Client

TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImUxOTdmZGY2LTZmN2ItNDU3Ni1iZjk4LTM2YWYxZjlmMjc3MSIsImlhdCI6MTY0NzYyODkzMywic3ViIjoiZGV2ZWxvcGVyLzExY2MwYjA5LTFmNWEtNmMyNi0xNGY1LTRmNzA3OGRmN2YwNiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEwOS4yNTIuMTEuMTU5Il0sInR5cGUiOiJjbGllbnQifV19.Wj1yrxAOf6ZQLTcRlbRgZo50bkhMAeEt6rL6UX1cASOK_GF4butmNmh7OSyrP1Ua0_zdj3q6ilALTO8VUKVGqA"

pytestmark = pytest.mark.asyncio


@pytest_asyncio.fixture
async def default_client():
    client = Client(TOKEN)
    yield client
    await client.close()
